import {
  Archive,
  BarChart,
  Bed,
  Beer,
  BookOpen,
  Briefcase,
  Calendar,
  Car,
  CheckCircle,
  Clock,
  Coffee,
  CreditCard,
  DollarSign,
  FastForward,
  FileText,
  Gamepad,
  Gift,
  Globe,
  Home,
  Laptop,
  Lightbulb,
  MapPin,
  Music,
  Paintbrush,
  PenTool,
  Phone,
  PhoneCall,
  Pizza,
  Plane,
  Scissors,
  Shield,
  Shirt,
  ShoppingCart,
  Speaker,
  Star,
  Umbrella,
  Wallet,
} from 'lucide-react' // Импортируем необходимые иконки

export const availableIcons = [
  { name: 'Home', icon: <Home size={20} /> },
  { name: 'DollarSign', icon: <DollarSign size={20} /> },
  { name: 'CreditCard', icon: <CreditCard size={20} /> },
  { name: 'ShoppingCart', icon: <ShoppingCart size={20} /> },
  { name: 'Coffee', icon: <Coffee size={20} /> },
  { name: 'Car', icon: <Car size={20} /> },
  { name: 'Pizza', icon: <Pizza size={20} /> },
  { name: 'Gift', icon: <Gift size={20} /> },
  { name: 'BarChart', icon: <BarChart size={20} /> },
  { name: 'BookOpen', icon: <BookOpen size={20} /> },

  { name: 'FileText', icon: <FileText size={20} /> },
  { name: 'Globe', icon: <Globe size={20} /> },
  { name: 'Umbrella', icon: <Umbrella size={20} /> },
  { name: 'Wallet', icon: <Wallet size={20} /> },
  { name: 'PenTool', icon: <PenTool size={20} /> },
  { name: 'Music', icon: <Music size={20} /> },
  { name: 'PaintBrush', icon: <Paintbrush size={20} /> },
  { name: 'Beer', icon: <Beer size={20} /> },
  { name: 'FastForward', icon: <FastForward size={20} /> },
  { name: 'Phone', icon: <Phone size={20} /> },
  { name: 'Laptop', icon: <Laptop size={20} /> },
  { name: 'Calendar', icon: <Calendar size={20} /> },
  { name: 'Plane', icon: <Plane size={20} /> },
  { name: 'Scissors', icon: <Scissors size={20} /> },
  { name: 'Speaker', icon: <Speaker size={20} /> },
  { name: 'CheckCircle', icon: <CheckCircle size={20} /> },
  { name: 'Clock', icon: <Clock size={20} /> },
  { name: 'Star', icon: <Star size={20} /> },
  { name: 'LightBulb', icon: <Lightbulb size={20} /> },
  { name: 'Bed', icon: <Bed size={20} /> },
  { name: 'Gamepad', icon: <Gamepad size={20} /> },
  { name: 'Shield', icon: <Shield size={20} /> },
  { name: 'PhoneCall', icon: <PhoneCall size={20} /> },
  { name: 'TShirt', icon: <Shirt size={20} /> },
  { name: 'MapPin', icon: <MapPin size={20} /> },
  { name: 'Briefcase', icon: <Briefcase size={20} /> },
  { name: 'Archive', icon: <Archive size={20} /> },
]
